In [1]:
import pandas as pandas
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt


from mpl_toolkits.basemap import Basemap

ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

In [1]:
pip install basemap

Collecting basemap
  ERROR: Could not find a version that satisfies the requirement basemap (from versions: none)
ERROR: No matching distribution found for basemap
Note: you may need to restart the kernel to use updated packages.

In [4]:
nldata = pandas.read_csv('nl.csv')

In [8]:
nldata

,city,lat,lng,country,iso2,admin,capital,population,population_proper
0,The Hague,52.083333,4.300000,Netherlands,NL,Zuid-Holland,primary,1406000.0,501725.0
1,Amsterdam,52.350000,4.916667,Netherlands,NL,Noord-Holland,primary,1031000.0,741636.0
2,Rotterdam,51.916667,4.500000,Netherlands,NL,Zuid-Holland,minor,1005000.0,598199.0
3,Utrecht,52.093813,5.119095,Netherlands,NL,Utrecht,admin,640000.0,316448.0
4,Eindhoven,51.450000,5.466667,Netherlands,NL,Noord-Brabant,minor,398053.0,209620.0
...,...,...,...,...,...,...,...,...,...
403,Wassenaar,52.110844,4.355982,Netherlands,NL,Zuid-Holland,minor,NaN,NaN
404,Geldermalsen,51.883333,5.300000,Netherlands,NL,Gelderland,minor,NaN,NaN
405,Dordrecht,51.800653,4.698199,Netherlands,NL,Zuid-Holland,minor,NaN,NaN
406,Rijswijk,52.025498,4.310793,Netherlands,NL,Zuid-Holland,minor,NaN,NaN
407,Rijssen,52.308315,6.519603,Netherlands,NL,Overijssel,minor,NaN,NaN

In [14]:
lat = nldata['lat'].values
lon = nldata['lng'].values
population = nldata['population'].values

In [13]:
fig = plt.figure(figsize=(8, 8))
m = Basemap(projection='lcc', resolution='h', 
            lat_0=37.5, lon_0=-119,
            width=1E6, height=1.2E6)
m.shadedrelief()
m.drawcoastlines(color='gray')
m.drawcountries(color='gray')
m.drawstates(color='gray')

NameError: name 'plt' is not defined